INSERT INTO LIKEANDSHARE.LIVRE (NOM_ARTISTE, TITRE, GENRE_LITTERAIRE) VALUES ('Amélie Nothomb', 'L''hygiène de l''assassin', 'roman');
INSERT INTO LIKEANDSHARE.LIVRE (NOM_ARTISTE, TITRE, GENRE_LITTERAIRE) VALUES ('Marc Levy', 'Et si c''était vrai', 'roman');
INSERT INTO LIKEANDSHARE.LIVRE (NOM_ARTISTE, TITRE, GENRE_LITTERAIRE) VALUES ('Marc Levy', 'Le premier jour', 'roman');
INSERT INTO LIKEANDSHARE.LIVRE (NOM_ARTISTE, TITRE, GENRE_LITTERAIRE) VALUES ('Amélie Nothomb', 'Le Sabotage amoureux', 'roman');