INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE (NOM_ARTISTE, NB_SCROB_TOTAL) VALUES ('Amélie Nothomb', 2);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE (NOM_ARTISTE, NB_SCROB_TOTAL) VALUES ('Johnny Depp', 3);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE (NOM_ARTISTE, NB_SCROB_TOTAL) VALUES ('Johnny Hallyday', 3);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE (NOM_ARTISTE, NB_SCROB_TOTAL) VALUES ('Marc Levy', 3);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE (NOM_ARTISTE, NB_SCROB_TOTAL) VALUES ('Soprano', 4);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE (NOM_ARTISTE, NB_SCROB_TOTAL) VALUES ('Will Smith', 5);