INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE_SEMAINE (NOM_ARTISTE, NUM_SEMAINE, ANNEE, NB_SCROB_SEMAINE) VALUES ('Soprano', 20, 2017, 4);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE_SEMAINE (NOM_ARTISTE, NUM_SEMAINE, ANNEE, NB_SCROB_SEMAINE) VALUES ('Johnny Hallyday', 20, 2017, 3);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE_SEMAINE (NOM_ARTISTE, NUM_SEMAINE, ANNEE, NB_SCROB_SEMAINE) VALUES ('Johnny Depp', 20, 2017, 3);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE_SEMAINE (NOM_ARTISTE, NUM_SEMAINE, ANNEE, NB_SCROB_SEMAINE) VALUES ('Will Smith', 20, 2017, 5);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE_SEMAINE (NOM_ARTISTE, NUM_SEMAINE, ANNEE, NB_SCROB_SEMAINE) VALUES ('Amélie Nothomb', 20, 2017, 2);
INSERT INTO LIKEANDSHARE.V_SCROB_ARTISTE_SEMAINE (NOM_ARTISTE, NUM_SEMAINE, ANNEE, NB_SCROB_SEMAINE) VALUES ('Marc Levy', 20, 2017, 3);