INSERT INTO LIKEANDSHARE.TITRE_MUSICAL (NOM_ARTISTE, TITRE, DUREE, GENRE_MUSICAL, TYPE_ALBUM) VALUES ('Renaud', 'Mistral Gagnant', 2.47, 'autre', 'single');
INSERT INTO LIKEANDSHARE.TITRE_MUSICAL (NOM_ARTISTE, TITRE, DUREE, GENRE_MUSICAL, TYPE_ALBUM) VALUES ('Soprano', 'Clown', 3.01, 'rap', 'full');
INSERT INTO LIKEANDSHARE.TITRE_MUSICAL (NOM_ARTISTE, TITRE, DUREE, GENRE_MUSICAL, TYPE_ALBUM) VALUES ('Johnny Hallyday', 'Allumer le feu', 5.29, 'rock', 'single');
INSERT INTO LIKEANDSHARE.TITRE_MUSICAL (NOM_ARTISTE, TITRE, DUREE, GENRE_MUSICAL, TYPE_ALBUM) VALUES ('Soprano', 'Roule', 3.50, 'rap', 'full');
INSERT INTO LIKEANDSHARE.TITRE_MUSICAL (NOM_ARTISTE, TITRE, DUREE, GENRE_MUSICAL, TYPE_ALBUM) VALUES ('Johnny Hallyday', 'Ma gueule', 3.53, 'rock', 'full');