INSERT INTO LIKEANDSHARE.FILM (NOM_ARTISTE, TITRE, GENRE_CINEMA) VALUES ('Johnny Depp', 'Pirate des caraïbes', 'autre');
INSERT INTO LIKEANDSHARE.FILM (NOM_ARTISTE, TITRE, GENRE_CINEMA) VALUES ('Johnny Depp', 'Alice au pays des Merveilles', 'SF');
INSERT INTO LIKEANDSHARE.FILM (NOM_ARTISTE, TITRE, GENRE_CINEMA) VALUES ('Will Smith', 'IRobot', 'SF');
INSERT INTO LIKEANDSHARE.FILM (NOM_ARTISTE, TITRE, GENRE_CINEMA) VALUES ('Will Smith', 'Je suis un légende', 'horreur');
INSERT INTO LIKEANDSHARE.FILM (NOM_ARTISTE, TITRE, GENRE_CINEMA) VALUES ('Will Smith', 'Diversion', 'autre');