INSERT INTO LIKEANDSHARE.UTILISATEUR (PSEUDO, MOT_DE_PASSE, CATEGORIE_AGE, CODE_POSTAL, ADMINISTRATEUR) VALUES ('zorro', 'masque1', '31-101', '88000', 0);
INSERT INTO LIKEANDSHARE.UTILISATEUR (PSEUDO, MOT_DE_PASSE, CATEGORIE_AGE, CODE_POSTAL, ADMINISTRATEUR) VALUES ('theMask', 'vert78', '31-101', '45000', 0);
INSERT INTO LIKEANDSHARE.UTILISATEUR (PSEUDO, MOT_DE_PASSE, CATEGORIE_AGE, CODE_POSTAL, ADMINISTRATEUR) VALUES ('fred87', '123abc', '0-20', '45000', 0);
INSERT INTO LIKEANDSHARE.UTILISATEUR (PSEUDO, MOT_DE_PASSE, CATEGORIE_AGE, CODE_POSTAL, ADMINISTRATEUR) VALUES ('cyril', 'basile1', '21-30', '54600', 1);
INSERT INTO LIKEANDSHARE.UTILISATEUR (PSEUDO, MOT_DE_PASSE, CATEGORIE_AGE, CODE_POSTAL, ADMINISTRATEUR) VALUES ('valentin', 'bonnal2', '21-30', '54000', 0);