INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Johnny Hallyday', 'Smet', 'Jean-Philippe');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Renaud', 'Séchan', 'Renaud');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Soprano', 'M''Roumbaba', 'Saïd');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Will Smith', 'Smith', 'Willard Christopher');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Marc Levy', 'Levy', 'Marc');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Johnny Depp', 'Depp', 'Johnny');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Margot Robbie', 'Robbie', 'Margot');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Victor Hugo', 'Hugo', 'Victor');
INSERT INTO LIKEANDSHARE.ARTISTE (NOM_ARTISTE, NOM, PRENOM) VALUES ('Amélie Nothomb', 'Nothomb', 'Amélie');